config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :reviews
  end

  

  get 'sessions/new'

  get 'sessions/show'

  delete '/logout', to: 'sessions#destroy'
  
  get "/auth/:provider/callback" => "sessions#create"
  
  get 'auth/logout' => 'sessions#destroy'

  get 'sessions/create'

  get 'sessions/destroy'

  

   root 'sessions#new'

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :for_user, class_name: 'User', foreign_key: 'for_user_id'
  belongs_to :by_user, class_name: 'User', foreign_key: 'by_user_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews_for_me, class_name: "Review", foreign_key: "for_user_id"
  has_many :reviews_by_me, class_name: "Review", foreign_key: "by_user_id"

  # setting parameters for geocode gem
  geocoded_by :full_address
  #geocode won't run until after validations
  after_validation :geocode

  def full_address
  	[address, city, state, zipcode].join(', ')
  end	

  class << self
	  def from_omniauth(auth_hash)
	    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
	    user.first_name = auth_hash['info']['first_name']
	    user.last_name = auth_hash['info']['last_name']
	    user.image = auth_hash['info']['image']
	    user.email = auth_hash['info']['email']
	    user.url = auth_hash['info']['urls'][user.provider.capitalize]
	    user.save!
	    user
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #makes current user available to ALL Controllers.
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #RecordNotFound exception raised by ActiveRecord
    rescue ActiveRecord::RecordNotFound
  end
  # makes current user available in every view
  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    @review = Review.new(review_params)
    @review.for_user_id = params[:user_id]
    @review.by_user_id = current_user.id

    @review.save

    redirect_to user_path(@review.for_user_id)
  end

  def destroy
    @review = Review.destroy(params[:id])
  end

  def edit
  end

  def update
  end
  def review_params
    params.require(:review).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def show
    
  	@auth = session['auth']
  end

  def create
  	#render text: request.env['omniauth.auth'].to_yaml
  	# Fetches the OAuth response info
    # @auth = request.env['omniauth.auth']
    # session['auth'] = @auth
    # redirect_to sessions_show_path
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      puts @user
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.first_name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end
    
    if current_user.bio 
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
  	if current_user
      session.delete(:user_id)
      flash[:success] = 'See you!'
    end
    
    redirect_to root_path
  end

  def auth_failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users= User.all
    
  
    if params[:search].present?
      @users = User.near(params[:search], 50, :order => :distance)
    else
      @users = User.all
    end
  
    #renders json for google maps
    respond_to do |format|
     format.html {
       render
     }
     format.json {
       render json: @users
     }
    end
  end

  def show
    @user = User.find(params[:id])
    


    @review = Review.new
    @review.for_user_id = @user.id
    @review.by_user_id = current_user.id

    #renders json for google maps
    respond_to do |format|
     format.html {
       render
     }
     format.json {
       render json: @users
     }
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id = current_user.id
      session.delete(:user_id)
      @user.destroy
    end
    redirect_to root_path
  end

private

  ## Defining the paraments for the users
  def user_params
    params.require(:user).permit(:first_name, :last_name, :image, :bio, :phone, :email, :city, :state, :instructor, :provider, :student, :uid, :oauth_token, :oauth_expires_at, :address, :zipcode)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yoga4u</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

  <!-- Add the jQuery library from CDN -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

  <!-- Add the google maps library -->
  <script src="//maps.googleapis.com/maps/api/js"></script>

  <!-- Add JS from the asset pipeline afterwards -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
<div class="navcolor">
  <nav class="navbar navbar-inverse navbar-fixed-top" >
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Yoga4U', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        
        <% if current_user %>
          <ul class="nav navbar-nav">
            
          
            <li><%= link_to 'Directory', users_path %></li>
          </ul>
          <ul class="nav navbar-nav pull-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.image, alt: current_user.first_name %><%= current_user.first_name %> <%= current_user.last_name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', user_path(current_user.id) %></li>
              <li><%= link_to 'Edit', edit_user_path(current_user.id) %></li>
              <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
            </ul>
          </li>
          <!-- <ul class="nav navbar-nav pull-right">
            <li><%= image_tag current_user.image, alt: current_user.first_name %></li>
            <li><%= link_to 'Profile', user_path(current_user.id) %></li>
            <li><%= link_to 'Account', edit_user_path(current_user.id) %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul> -->
        <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Sign in via Facebook', '/auth/facebook' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</div>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/pages/_welcome.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Authenticate via facebook to get started.</p>
</div>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Authenticate via facebook</p>
</div>
<% if current_user %>
  <div class="page-header">
    <h1>Here is some info about you...</h1>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <ul>
        <li><strong>Name:</strong> <%= current_user.first_name %></li>
        <li><strong>Provider:</strong> <%= current_user.provider %></li>
        <li><strong>uID:</strong> <%= current_user.uid %></li>
        <li><strong>Location:</strong> <%= current_user.location %></li>
        <li><strong>Avatar URL:</strong> <%= current_user.image %></li>
        <li><strong>URL:</strong> <%= current_user.url %></li>
      </ul>
    </div>
  </div>
<% else %>
  <%= render 'welcome' %>
<% end %>

app/views/reviews/_form.html.erb
<h4>Post a Review</h4>

<%= form_for [ @user, @review ] do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title, :class => "form-control" %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body, :class => "form-control" %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>
<%= render partial: 'reviews/form' %>

app/views/users/_instructor.html.erb
Instructor
<h3><%= @user.first_name + " " + @user.last_name %></h3>
<br>
<%=image_tag(@user.image, size: "100x100")%>
<br>

<h4>Bio</h4>
<%= @user.bio %>
<br>
<h4>Location</h4>
<%= @user.city %>,
<%= @user.state %>,
<%= @user.zipcode %>

<hr>

app/views/users/_nearby.html.erb
<h3>Yogis Nearby</h3>

<% for user in @user.nearbys(10) %>
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to user.first_name, user %> (<%= user.distance.round(2) %> miles)
  </div>
</div>
<% end %>

app/views/users/_review.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= review.by_user.first_name + " " + review.by_user.last_name %></h3>
    <p class="review_time">Posted <%= distance_of_time_in_words(review.created_at, review.created_at) %> later</p>
  </div>
  <div class="panel-body">
    <%= review.body %>
  </div>
</div>

app/views/users/_student.html.erb
Student
<h3><%= @user.first_name + " " + @user.last_name %></h3>
<br>
<%=image_tag(@user.image, size: "100x100")%>
<br>

<h4>Bio</h4>
<%= @user.bio %>
<br>
<h4>Location</h4>
<%= @user.city %>,
<%= @user.state %>,
<%= @user.zipcode %>

<hr>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone, required: true %>
  </p>
  <p>
    <%= f.label :bio %><br />
    <%= f.text_area :bio, required: true %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address, required: true %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city, required: true %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state, required: true %>
  </p>
  <p>
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode, required: true %>
  </p>
  <%#= f.radio_button_tag :instructor, false %>
  <%#= f.radio_button_tag(:instructor, true) %>
  <%#= label_tag(:instructor, "instructor") %>
  <%#= radio_button_tag(:age, "adult") %>
  <%#= label_tag(:age_adult, "I'm over 21") %>
  <div class="field">
    <%= f.label "Intructor" %> <br />
    <%= f.radio_button :instructor, true %> <br />
  </div>
  <div class="field">
    <%= f.label "Student" %> <br />
    <%= f.radio_button :student, true %> <br />
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= button_to "Delete my account", user_path, :data => { :confirm => "Are you sure?" }, :method => :delete, class: "btn btn-danger" %>

app/views/users/index.html.erb
<h2>Yoga4U Directory</h2>
<% @users.each do |user| %>
	<%#= user.first_name %><%#= user.last_name %>
<% end %>

<% for user in @users %>
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to user.first_name + " " + user.last_name, user %>
  </div>
</div>
<% end %>

<div id="googleMap" style="width:500px;height:380px;"></div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% if @user.instructor == true %>
        <%= render 'instructor' %>
        

<% elsif @user.student == true %>
        <%= render 'student' %>
        
<% end %>
<%#= render partial: 'users/review', collection: @user.reviews_for_me %>
<%#= render partial: 'reviews/form' %>
<h2>Reviews</h2>
<%= render partial: 'users/review', collection: @user.reviews_for_me %>
<%= render partial: 'reviews/form' %>
<%= render partial: 'users/nearby' %>